services:
  workspace:
    image: mcr.microsoft.com/devcontainers/javascript-node:20-bookworm
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    networks:
      - app-network
    depends_on:
      - backend
      - frontend
